# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arch',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AutoCase',
            fields=[
                ('id', models.CharField(max_length=65535, primary_key=True, serialize=False)),
                ('start_commit', models.CharField(blank=True, max_length=255)),
                ('end_commit', models.CharField(blank=True, max_length=255)),
                ('archs', models.ManyToManyField(blank=True, related_name='autocases', to='caselink.Arch')),
            ],
        ),
        migrations.CreateModel(
            name='AutoCaseFailure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('failure_regex', models.CharField(max_length=65535)),
                ('autocase_pattern', models.CharField(max_length=65535)),
                ('autocases', models.ManyToManyField(related_name='failures', to='caselink.AutoCase')),
            ],
        ),
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='CaseLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autocase_pattern', models.CharField(max_length=65535)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('autocases', models.ManyToManyField(blank=True, related_name='caselinks', to='caselink.AutoCase')),
                ('error_related', models.ManyToManyField(blank=True, related_name='_caselink_error_related_+', to='caselink.CaseLink')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=65535)),
                ('components', models.ManyToManyField(to='caselink.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('message', models.CharField(blank=True, max_length=65535)),
            ],
        ),
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=65535)),
                ('automation', models.CharField(blank=True, default='notautomated', max_length=255)),
                ('commit', models.CharField(blank=True, max_length=255)),
                ('need_automation', models.BooleanField(default=False)),
                ('maitai_id', models.CharField(blank=True, max_length=65535)),
                ('archs', models.ManyToManyField(blank=True, related_name='workitems', to='caselink.Arch')),
                ('documents', models.ManyToManyField(blank=True, related_name='workitems', to='caselink.Document')),
                ('error_related', models.ManyToManyField(blank=True, related_name='_workitem_error_related_+', to='caselink.WorkItem')),
                ('errors', models.ManyToManyField(blank=True, related_name='workitems', to='caselink.Error')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workitems', to='caselink.Project')),
                ('updated', models.DateTimeField(auto_now_add=True, default=datetime.datetime(1990, 1, 1, 1, 1, tzinfo=utc))),
                ('comment', models.CharField(blank=True, max_length=65565, null=True)),
                ('jira_id', models.CharField(blank=True, max_length=65535, null=True)),
                ('changes', models.TextField(blank=True, null=True)),
                ('confirmed', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='caselink',
            name='errors',
            field=models.ManyToManyField(blank=True, related_name='caselinks', to='caselink.Error'),
        ),
        migrations.AddField(
            model_name='caselink',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caselinks', to='caselink.Framework'),
        ),
        migrations.AddField(
            model_name='caselink',
            name='workitem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caselinks', to='caselink.WorkItem'),
        ),
        migrations.AddField(
            model_name='autocasefailure',
            name='errors',
            field=models.ManyToManyField(blank=True, related_name='autocase_failures', to='caselink.Error'),
        ),
        migrations.AddField(
            model_name='autocasefailure',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autocase_failures', to='caselink.Framework'),
        ),
        migrations.AddField(
            model_name='autocase',
            name='errors',
            field=models.ManyToManyField(blank=True, related_name='autocases', to='caselink.Error'),
        ),
        migrations.AddField(
            model_name='autocase',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autocases', to='caselink.Framework'),
        ),
        migrations.AlterUniqueTogether(
            name='caselink',
            unique_together=set([('workitem', 'autocase_pattern')]),
        ),
        migrations.AlterField(
            model_name='autocasefailure',
            name='autocases',
            field=models.ManyToManyField(blank=True, related_name='failures', to='caselink.AutoCase'),
        ),
        migrations.RemoveField(
            model_name='autocasefailure',
            name='type',
        ),
        migrations.AlterField(
            model_name='autocasefailure',
            name='autocases',
            field=models.ManyToManyField(blank=True, related_name='autocase_failures', to='caselink.AutoCase'),
        ),
        migrations.AlterUniqueTogether(
            name='autocasefailure',
            unique_together=set([('failure_regex', 'autocase_pattern')]),
        ),
        migrations.AlterField(
            model_name='caselink',
            name='workitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caselinks', to='caselink.WorkItem'),
        ),
        migrations.AddField(
            model_name='autocase',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='autocases', to='caselink.Component'),
        ),
        migrations.AlterField(
            model_name='document',
            name='components',
            field=models.ManyToManyField(blank=True, to='caselink.Component'),
        ),
        migrations.AlterField(
            model_name='caselink',
            name='workitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caselinks', to='caselink.WorkItem'),
        ),
        migrations.AlterField(
            model_name='autocase',
            name='end_commit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='autocase',
            name='start_commit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='autocase',
            name='pr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.RenameModel(
            old_name='CaseLink',
            new_name='Linkage',
        ),
        migrations.RemoveField(
            model_name='linkage',
            name='title',
        ),
        migrations.CreateModel(
            name='BlackListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('autocase_failures', models.ManyToManyField(related_name='blacklist_entries', to='caselink.AutoCaseFailure')),
                ('bugs', models.ManyToManyField(blank=True, related_name='blacklist_entries', to='caselink.Bug')),
                ('errors', models.ManyToManyField(blank=True, related_name='blacklist_entries', to='caselink.Error')),
                ('workitems', models.ManyToManyField(blank=True, related_name='blacklist_entries', to='caselink.WorkItem')),
            ],
        ),
        migrations.AlterField(
            model_name='linkage',
            name='autocases',
            field=models.ManyToManyField(blank=True, related_name='linkages', to='caselink.AutoCase'),
        ),
        migrations.AlterField(
            model_name='linkage',
            name='errors',
            field=models.ManyToManyField(blank=True, related_name='linkages', to='caselink.Error'),
        ),
        migrations.AlterField(
            model_name='linkage',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linkages', to='caselink.Framework'),
        ),
        migrations.AlterField(
            model_name='linkage',
            name='workitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linkages', to='caselink.WorkItem'),
        ),
    ]
