# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0001_squashed_0018_auto_20170222_1422'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='jira_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
