# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-14 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0013_auto_20161130_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='autocasefailure',
            name='bug',
        ),
        migrations.RemoveField(
            model_name='autocasefailure',
            name='type',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='bug',
            name='manualcases',
        ),
        migrations.AlterField(
            model_name='autocasefailure',
            name='autocases',
            field=models.ManyToManyField(blank=True, related_name='autocase_failures', to='caselink.AutoCase'),
        ),
        migrations.AlterField(
            model_name='autocasefailure',
            name='errors',
            field=models.ManyToManyField(related_name='autocase_failures', to='caselink.Error'),
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='autocase_failures',
            field=models.ManyToManyField(related_name='black_list_entries', to='caselink.AutoCaseFailure'),
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='bugs',
            field=models.ManyToManyField(blank=True, related_name='black_list_entries', to='caselink.Bug'),
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='errors',
            field=models.ManyToManyField(blank=True, related_name='black_list_entries', to='caselink.Error'),
        ),
        migrations.AddField(
            model_name='blacklistentry',
            name='manualcases',
            field=models.ManyToManyField(blank=True, related_name='black_list_entries', to='caselink.WorkItem'),
        ),
    ]
