# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-21 06:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0015_auto_20170217_0717'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklistentry',
            old_name='manualcases',
            new_name='workitems',
        ),
        migrations.AlterField(
            model_name='linkage',
            name='autocases',
            field=models.ManyToManyField(blank=True, related_name='linkages', to='caselink.AutoCase'),
        ),
        migrations.AlterField(
            model_name='linkage',
            name='errors',
            field=models.ManyToManyField(blank=True, related_name='linkages', to='caselink.Error'),
        ),
        migrations.AlterField(
            model_name='linkage',
            name='framework',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linkages', to='caselink.Framework'),
        ),
        migrations.AlterField(
            model_name='linkage',
            name='workitem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linkages', to='caselink.WorkItem'),
        ),
    ]
