# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-22 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0016_auto_20170221_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistentry',
            name='autocase_failures',
            field=models.ManyToManyField(related_name='blacklist_entries', to='caselink.AutoCaseFailure'),
        ),
        migrations.AlterField(
            model_name='blacklistentry',
            name='bugs',
            field=models.ManyToManyField(blank=True, related_name='blacklist_entries', to='caselink.Bug'),
        ),
        migrations.AlterField(
            model_name='blacklistentry',
            name='errors',
            field=models.ManyToManyField(blank=True, related_name='blacklist_entries', to='caselink.Error'),
        ),
        migrations.AlterField(
            model_name='blacklistentry',
            name='workitems',
            field=models.ManyToManyField(blank=True, related_name='blacklist_entries', to='caselink.WorkItem'),
        ),
    ]
