# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caselink', '0017_auto_20170222_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='automation',
            field=models.CharField(blank=True, default='notautomated', max_length=255),
        ),
    ]
